# Generated by Django 4.0.4 on 2022-07-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_address'),
        ('myapp', '0005_alter_order_order_date'),
    ]

    operations = [
    ]
