# Generated by Django 4.0.6 on 2022-07-26 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_order_course_order_course_alter_order_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 19, 16, 29, 719822, tzinfo=utc)),
        ),
    ]
