# Generated by Django 4.0.6 on 2022-08-14 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.models.validateprice]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 2, 48, 3, 855826, tzinfo=utc)),
        ),
    ]
